version: '3.7'
services:
  btc-api:
    image: btc-api
    container_name: btc-api
    build: ./ 
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "$PORT:$PORT"
    volumes:
    - $PWD/$DB_PATH:/app/$DB_PATH